"""update vaccine table

Revision ID: d78d0cefd731
Revises: 23f8cc1b5e45
Create Date: 2022-05-01 17:06:21.370011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd78d0cefd731'
down_revision = '23f8cc1b5e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaccine_cards', sa.Column('vaccine_name', sa.String(), nullable=False))
    op.alter_column('vaccine_cards', 'first_shot_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('vaccine_cards', 'second_shot_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_unique_constraint(None, 'vaccine_cards', ['cpf'])
    op.drop_column('vaccine_cards', 'vacinne_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaccine_cards', sa.Column('vacinne_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vaccine_cards', type_='unique')
    op.alter_column('vaccine_cards', 'second_shot_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('vaccine_cards', 'first_shot_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('vaccine_cards', 'vaccine_name')
    # ### end Alembic commands ###
